### ISSUE TITLE
AWScala is currently setting Number Sets as String Sets

### ISSUE THREAD

**Issue by jdrphillips** [seratch/AWScala#118]
https://github.com/seratch/AWScala/blob/master/src/main/scala/awscala/dynamodbv2/AttributeValue.scala#L29

`withSS` should be `withNS`.

**Comment by jdrphillips** [comment]
Pull request: https://github.com/seratch/AWScala/pull/119

**Comment by seratch** [comment]
Thank you for your PR. Merged.
