### ISSUE TITLE
No default value for AttibuteValue's `l` field

### ISSUE THREAD

**Issue by adamnfish** [seratch/AWScala#140]
A recent change removed the default value for AttributeValue's `l` field. This means there are heaps of places where I've had to update test code to provide `Nil`.

I'm struggling to see a reason for this change. If there isn't one, can the default `Nil` be added? It looks like it may simply be an oversight that this parameter was added without  a default. I'm very happy to raise a PR to do so if that seems like a reasonable change?

**Comment by seratch** [comment]
Default value for `l` is reasonable for me. I'm looking forward to merging your pull request 👍
