### ISSUE TITLE
Not all AWS  regions supported in Region

### ISSUE THREAD

**Issue by francescoperera** [seratch/AWScala#142]
Does AWScala  handle Seoul,Mumbai ,Ohio, Montreal, London as a Region?  If so, can you point me to it?
I don't see  them defined in Region0.scala

**Comment by seratch** [comment]
They should be handled correctly but they are just absent in Region0.scala. If you're in a hurry, would you send a pull request to fix that?

**Comment by francescoperera** [comment]
@seratch  thanks for the reply. Not in a hurry right now but will send a PR when I do have some time.

**Comment by rogerzxu** [comment]
I don't believe these missing regions: ap-south-1, ca-central-1, us-east-2, eu-west-2 will work at using Region class, as the underlying amazon java sdk is on 1.11.57 and is missing these 4 enums from the [latest](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html). 

You can still access these regions though if the regions are explicity defined in the endpoints and are set with `setEndpoint`.
