### ISSUE TITLE
Queue#messages receives only one message at a time

### ISSUE THREAD

**Issue by rogerzxu** [seratch/AWScala#163]
The naming and the type of `awscala.sqs.Queue.messages(): Seq[Message]` implies that the queue polls for multiple messages at once.

However, through following the calls and through testing, I see that it eventually calls `SQS#def receiveMessage(queue: Queue): Seq[Message] = receiveMessage(queue, 1)`, where 1 is the maximum number of messages to be received.

Either the naming/type of the function in `Queue` should be altered to reflect this behavior, or it should use a different call to SQS so that it can receive multiple messages.

**Comment by leoromanovsky** [comment]
I believe the AWS API by default returns one message. It would be useful to allow users to use the Batch API and request up to 10 messages.

**Comment by seratch** [comment]
Fair enough. I will change the method call to specify 10 as the maximum size.
