### ISSUE TITLE
java.lang.noSuchFieldError: CN_NORTHWEST_1

### ISSUE THREAD

**Issue by latrilla** [seratch/AWScala#171]
A runtime error happens while trying to instanciate a S3 Bucket using the Maven 0.6.3 version : 
```
scala> import awscala._, s3._
implicit val s3 = S3.at(Region.EU_WEST_1)
import awscala._
import s3._

scala> java.lang.NoSuchFieldError: CN_NORTHWEST_1
  at awscala.Region0$.<init>(Region0.scala:33)
  at awscala.Region0$.<clinit>(Region0.scala)
  at awscala.package$.<init>(package.scala:3)
  at awscala.package$.<clinit>(package.scala)
  ... 24 elided
```

**Comment by seratch** [comment]
Let me know your AWS Java SDK version. AWScala 0.6.3 is compatible with AWS Java SDK 1.11.285.

**Comment by latrilla** [comment]
I'm on the 1.11.183 version, indeed updating to the 1.11.285 worked. Sorry about that, thanks

**Comment by IvanGuardado** [comment]
I'm getting the same error... using the 0.7.1

```
User class threw exception: java.lang.NoSuchFieldError: CN_NORTHWEST_1
```

```scala
libraryDependencies += "com.github.seratch" %% "awscala-s3" % "0.7.1"
```

Could anyone help me with this?

Thanks!

**Comment by seratch** [comment]
@IvanGuardado Can you check the version of not AWScala but AWS Java SDK?

**Comment by IvanGuardado** [comment]
@seratch The AWS Java SDK installed version is `2.8.5`. It's automatically installed by the `awscala` dependency.

**Comment by seratch** [comment]
@IvanGuardado I don't believe it. AWScala 0.7.1 depends on 1.11.285.
https://github.com/seratch/AWScala/blob/0.7.1/build.sbt#L57

**Comment by IvanGuardado** [comment]
Totally true! I had the number `285` in my mind and I wrote `2.8.5`, sorry.

```
Resolving com.amazonaws#aws-java-sdk-s3;1.11.285
```
