### ISSUE TITLE
NullPointerException occurred when describing dynamodb table without BillingMode

### ISSUE THREAD

**Issue by feleio** [seratch/AWScala#199]
https://github.com/seratch/AWScala/blob/master/dynamodb/src/main/scala/awscala/dynamodbv2/TableMeta.scala#L103

I ve got null pointer exception from this line. There might be some dynamo table doesn't give you bill mode summary?

related change:
#195
@kimxogus

**Comment by feleio** [comment]
#195
@kimxogus

**Comment by feleio** [comment]
Thanks

**Comment by thestephenstanton** [comment]
How was this able to make it in 8.2? Just curious. I think I looked and the build for the commit that the breaking code was added to, failed.

**Comment by adamnfish** [comment]
I see this is fixed in master, but there doesn't seem to be a release that includes it. Am I missing a release, or is this on purpose?

Thanks heaps for raising and fixing this everyone!

**Comment by apetross** [comment]
+1 having the same issue.  will there be a new release with the fix?

**Comment by seratch** [comment]
I just released version 0.8.3. The jars will be available on Maven Central repositories very soon.
