### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by orium** [seratch/AWScala#201]
Ref #190

**Comment by Quafadas** [comment]
Any news on this?

**Comment by jeffrey-aguilera** [comment]
I'm interested as well.

**Comment by seratch** [comment]
Indeed, it's about time to do that. Should we have a fork project of scala-ssh?

**Comment by adamnfish** [comment]
Looks like scala-ssh has updated, was that the last blocker to a 2.13 release of AWScala? Thank you everyone that's already been looking at this!

**Comment by note** [comment]
I opened a PR here: https://github.com/seratch/AWScala/pull/209
It compiles but tests fail for scala 2.13. Will try to take a look in a following days

**Comment by seratch** [comment]
#215 has been merged. I will release a new version soon.

**Comment by orium** [comment]
Hi @seratch.  Any news about a new release?  If there's anything that needs to be done I'm happy to help.

**Comment by seratch** [comment]
@orium Sorry for the delay! I just shipped it. The jars will be synched to maven central within a few hours.

**Comment by orium** [comment]
Awesome.  Thank you @seratch
