### ISSUE TITLE
Region object vs type alias

### ISSUE THREAD

**Issue by MasseGuillaume** [seratch/AWScala#63]
First, thanks for this project, it's really helpful.

I got a major bug in the scala 2.11.5 Repl: https://issues.scala-lang.org/browse/SI-9165

as pointed out in the comment, it may be because of the confusion between the [type alias Region](https://github.com/seratch/AWScala/blob/develop/src/main/scala/awscala/package.scala#L3) and the [object Region](https://github.com/seratch/AWScala/blob/develop/src/main/scala/awscala/Region.scala#L3). Is there away we can remove this ambuiguity ?

**Comment by fcofdez** [comment]
I've the same problem, is there a way to solve this?

**Comment by MasseGuillaume** [comment]
```scala
val credentials = Credentials(key, secret)
implicit val s3Client = S3(credentials)
s3Client.setRegion(Region("us-east-1"))
```

**Comment by lihaoyi** [comment]
I've got the same problem too. @MasseGuillaume what is the code example and how does it relate to the bug? =P

**Comment by MasseGuillaume** [comment]
@lihaoyi I knew you were running scala secretly at dropbox  :P

Let me see what's the solution for this during the weekend
