### ISSUE TITLE
Cannot get S3 buckets in US_EAST_1 region

### ISSUE THREAD

**Issue by eswenson1** [seratch/AWScala#70]
If I use the following code:

```scala
import awscala._
import s3._

object AwsTest {
  def main(args: Array[String]): Unit = {
    implicit val s3 = S3.at(Region.US_EAST_1)
    val bucket = s3.bucket("foo").get
    println(bucket.totalSize)
  }
}
```

I get the error:

```
[error] (run-main-c) java.lang.IllegalArgumentException: Cannot create enum from us-east-1 value!
java.lang.IllegalArgumentException: Cannot create enum from us-east-1 value!
	at com.amazonaws.services.s3.model.Region.fromValue(Region.java:224)
	at awscala.s3.S3$class.at(S3.scala:28)
	at awscala.s3.S3Client.at(S3.scala:239)
	at awscala.s3.S3$.apply(S3.scala:11)
	at awscala.s3.S3$.at(S3.scala:15)
```

Since I created my buckets in the us-east-1 region, and AWScala uses US_WEST_1 as the default region (unlike the AWS SDK for Java, which uses us-east-1 as the default region), while I can list buckets, I can do no operations on specific buckets because the Region defaults to US_WEST_1 and I'm unable to override this as you can see above.

If I change the definition of the s3 var to just S3(), then I get the following error from the AWS SDK:

```
[error] (run-main-e) com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 35046B17DA2581B0), S3 Extended Request ID: iOteNJlE7qEkrQ6F+aMfpBeXgKjdZV0aJtB2BJCPgAQkDqTjPIgMoyvftB9kHGIdeAENGrrA0cQ=
```

**Comment by seratch** [comment]
I just read Java SDK source code. `US Standard (us-east-1)` should be null here.

https://github.com/aws/aws-sdk-java/blob/1.8.0/src/main/java/com/amazonaws/services/s3/model/Region.java#L53

If you find a work around, please make a pull request to improve this.

**Comment by eswenson1** [comment]
That's correct, but due to the way AWScala is implemented, I don't see a way of specifying this region from this library. It works fine from the Java AWS SDK.

**Comment by eswenson1** [comment]
More specifically,  none of the following will work:

Region(null)
Region(None)
Region("us-east-1")
Region("US")

as a parameter to S3().at(...)

The issue appears to be due to the fact that com.amazonaws.servies.s3.model.Region.fromValue does not accept us-east-1, but only null or "US" as a means of getting the us-east-1 region.  But the code in AWScala uses the com.amazonaws.regions.Regions.fromName method to get the "string" that will get passed to com.amazonaws.servies.s3.model.Region.fromValue, and com.amazonaws.regions.Regions.fromName uses "us-east-1" to represent that region.  Consequently, you cannot specify Regions.US_EAST_1 because this results in an com.amazonaws.servies.s3.model.Region whose name is "us-east-1" and this gets passed to com.amazonaws.servies.s3.model.Region.fromValue, which doesn't accept "us-east-1" as a way of getting this region. So I don't see any way around this given the current design of AWScala. Do you?

**Comment by eswenson1** [comment]
I came up with a hack that appears to make things work.  In S3.scala, add the following function:

  def s3RegionHack(regionName: String): String = {
    regionName match {
      case "us-east-1" => "US"
      case _ => regionName
    }
  }

And change the code that follows to use it.  I'll submit a PR for this.

  private[this] var region: aws.model.Region = aws.model.Region.fromValue(s3RegsionHack(Region.default.getName))

  def at(region: Region): S3 = {
    this.setRegion(region)
    this.region = aws.model.Region.fromValue(s3RegionHack(region.getName))
    this
  }

**Comment by seratch** [comment]
Cool. Please change the `s3RegionHack` method as a private method on the PR.
