### ISSUE TITLE
s3 putObject InputStream

### ISSUE THREAD

**Issue by MasseGuillaume** [seratch/AWScala#76]
It's available in the sdk: https://github.com/aws/aws-sdk-java/blob/1.8.0/src/main/java/com/amazonaws/services/s3/AmazonS3.java#L2187
but not in this project: https://github.com/seratch/AWScala/blob/master/src/main/scala/awscala/s3/S3.scala#L208

**Comment by seratch** [comment]
Supporting this would be fine. If you need this right now, please make a pull request.

**Comment by seratch** [comment]
Fixed by #91
