### ISSUE TITLE
Where do I configure my AWS credentials?

### ISSUE THREAD

**Issue by nykolaslima** [seratch/AWScala#84]
The README shows pretty well how to use the library features but I couldn't find how to configure my AWS credentials(key and secret). How can I do it?

I believe we could add it to README also.

**Comment by seratch** [comment]
Thanks for your feedback. I just updated REAME. https://github.com/seratch/AWScala/commit/4d2f167aed14f4374f048e8245151c99bdaae83a

**Comment by seratch** [comment]
Let me close this issue.

**Comment by nykolaslima** [comment]
:+1:

**Comment by nykolaslima** [comment]
@seratch actually using environment variable is not working with AWScala.

I've configured those environment variables: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

And i've created the S3 instance this way: `val s3 = S3()`

**Comment by ilanbiala** [comment]
@seratch is there no way to authenticate via the AWScala package? It would be so much easier to do something like:

```scala
implicit val sqs = SQS.at(Region.US_EAST_1, new AWSCalaCredentials("", ""))
```

**Comment by ilanbiala** [comment]
@nykolaslima have you been able to authenticate with environment variables? I have only been able to with a credentials file in `~/.aws`.

**Comment by nykolaslima** [comment]
@ilanbiala I could not get this working with environment variables.

I had to create a code in my project to load environment variable and instantiate the `S3` object.

**Comment by ilanbiala** [comment]
@seratch any ideas what's going on?
